# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 03:38


import django.db.models.deletion
from django.db import migrations, models

from wagtailmetadata.utils import get_image_model_string

IMAGE_MODEL = get_image_model_string()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0010_change_on_delete_behaviour'),
        ('wagtailcore', '0023_alter_page_revision_on_delete_behaviour'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMetadataPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_description', models.TextField()),
                ('card_type', models.CharField(choices=[('summary', 'Summary card'), ('summary_large_image', 'Summary card with large image')], max_length=128)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
                ('site_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=IMAGE_MODEL)),
            ],
        ),
    ]
